### ISSUE TITLE
请问可以用于多张图片上传的吗？

### ISSUE THREAD

**Issue by libozhi** [1977474741/image-cropper#34]
对应工具或者iOS或者Andriod的版本号

微信版本号

代码截图

重现步骤

期待的行为

实际的行为

**Comment by 1977474741** [comment]
不可以，哪有同时裁剪多张图片的？

**Comment by libozhi** [comment]
> 以

谢谢你开发了一个这个好用的裁切工具，让我能够快速开发~，开发这样的工具，需要什么样的知识吗？或者说应该怎么学习,学习什么技术？canvas吗? 感谢~！

**Comment by libozhi** [comment]
> 不可以，哪有同时裁剪多张图片的？
谢谢你开发了一个这个好用的裁切工具，让我能够快速开发~，开发这样的工具，需要什么样的知识吗？或者说应该怎么学习,学习什么技术？canvas吗? 感谢~！

**Comment by libozhi** [comment]
> 不可以，哪有同时裁剪多张图片的？

谢谢你开发了一个这个好用的裁切工具，让我能够快速开发~，开发这样的工具，需要什么样的知识吗？或者说应该怎么学习,学习什么技术？canvas吗? 感谢~！

**Comment by 1977474741** [comment]
js就好，都通用的
