### ISSUE TITLE
iphone真机图片会显示在左上角

### ISSUE THREAD

**Issue by XdyGoGo** [1977474741/image-cropper#48]
对应工具或者iOS或者Andriod的版本号

微信版本号

代码截图

重现步骤

期待的行为

实际的行为

**Comment by QiuXXX** [comment]
使用那个重置位置方法，会回到裁剪窗口中央

**Comment by xuwei-fe** [comment]
bug 是会一闪下

**Comment by wlgshf** [comment]
如果图片加载进来不在正中间，估计是组件样式有冲突的 主要看下 image 标签的样式 是不是有定义在app.wxss中

**Comment by QiuXXX** [comment]
Thanks！ 谢谢你的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "songc"<notifications@github.com&gt;; 
发送时间: 2020年4月2日(星期四) 下午3:17
收件人: "wx-plugin/image-cropper"<image-cropper@noreply.github.com&gt;; 
抄送: "邱星星"<1018972412@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wx-plugin/image-cropper] iphone真机图片会显示在左上角 (#48)





 
如果图片加载进来不在正中间，估计是组件样式有冲突的 主要看下 image 标签的样式 是不是有定义在app.wxss中

**Comment by Maximus-ckp** [comment]
我也遇到了这个问题，真机图片在初始时在左上角。
解决方案是在恰当的时间（比如 wx:if 对应值为 true 时），父组件调用 image-cropper 组件自己的重置图片方法：

setTimeout(()=>{
    this.cropper = this.selectComponent('#image-cropper')；
    this.cropper.imgReset()；
})
