### ISSUE TITLE
图片长度比宽度长的时候，图片在裁剪区位置偏左太多

### ISSUE THREAD

**Issue by Di-btt** [1977474741/image-cropper#66]
![image](https://user-images.githubusercontent.com/14688004/76493947-d0c56900-646e-11ea-8aa7-a91be2acb004.png)

**Comment by wlgshf** [comment]
同样问题，但我发现提供的小程序扫码测试demo没有问题呢？

**Comment by wlgshf** [comment]
我解决了 是自身原因 组件样式冲突导致的 主要看下image标签的样式

**Comment by henry8310** [comment]
> 我解决了 是自身原因 组件样式冲突导致的 主要看下image标签的样式

可否具体说下，刚遇到这个问题，不知道咋解决，多谢了

**Comment by HelloDB** [comment]
> > 我解决了 是自身原因 组件样式冲突导致的 主要看下image标签的样式
> 
> 可否具体说下，刚遇到这个问题，不知道咋解决，多谢了

如果正巧也是用的colorui的话确实会有image样式冲突，将max-width改大就正常了
