### ISSUE TITLE
建议裁剪框可以拖动

### ISSUE THREAD

**Issue by freespy** [1977474741/image-cropper#69]
最好能设置手指在裁剪框的时候拖动的是裁剪框，手指在裁剪框外面的时候，拖动的是图片，这样子更方便选取需要裁剪的图片。

**Comment by yhhwpp** [comment]
+1

**Comment by yhhwpp** [comment]
手机系统的自带裁剪的交互好一些，期待作者更新

**Comment by 1977474741** [comment]
设计的时候没考虑拖动裁剪框，因为移动图片完全可以实现裁剪，加了移动裁剪框就乱了，会影响用户体验。
别走pc端的思路，pc端因为屏幕大，可以在图片不动的条件下拖动裁剪框，但移动端屏幕小，如果把图片固定在那里只移动裁剪框，裁剪过程会受很多限制
