### ISSUE TITLE
表单数据没了

### ISSUE THREAD

**Issue by Joisle** [1977474741/image-cropper#71]
对应工具或者iOS或者Andriod的版本号
微信小程序
微信版本号
无
代码截图
源码demo
重现步骤
表单里用此控件先预填一些数据,当上传图片裁剪后展示的时候表单数据都没了
期待的行为
表单数据还是保持之前的填写状态
实际的行为
填写的表单数据都没了

**Comment by 1977474741** [comment]
这是业务代码的问题吧。。。仔细检查一下代码
